name: stats1
channels:
  - javascript
dependencies:
  - python=3.6   # or 2.7
  - bokeh=0.9.2
  - nodejs=0.10.*
  - apache-airflow==1.10.0
  - scikit-learn>=0.19.2
  - numpy>=1.14.1
  - pytest>=3.3.2
#  - pre-commit>=1.12.0
  - Sphinx>=1.7.6
#  - sphinx-rtd-theme>=0.4.1
  - numpydoc>=0.8.0